#!/usr/bin/env node
`use strict`
const Parser = require('rss-parser')
const parser = new Parser()
const fs = require('fs')

async function main() {
  const feedQiitaRaw = await parser.parseURL('https://qiita.com/basd4g/feed.atom')
  const feedQiita = feedQiitaRaw.items.map(feed => ({
    site: 'https://qiita.com/basd4g',
    title: feed.title,
    url: feed.link,
    isoDate: feed.isoDate,
    content: feed.content,
    contentSnippet: feed.contentSnippet,
  }))
  const feedHugoRaw = await parser.parseURL('https://memo.basd4g.net/posts/index.xml')
  const feedHugo = feedHugoRaw.items.map(feed => ({
    site: 'https://memo.basd4g.net',
    title: feed.title,
    url: 'https://memo.basd4g.net' + feed.link,
    isoDate: feed.isoDate,
    content: feed.content,
    contentSnippet: feed.contentSnippet,
  }))
  const feedHatenaRaw = await parser.parseURL('https://basd4g.hatenablog.com/rss')
  const feedHatena = feedHatenaRaw.items.map(feed => ({
    site: 'https://basd4g.hatenablog.com',
    title: feed.title,
    url: feed.link,
    isoDate: feed.isoDate,
    content: feed.content,
    contentSnippet: feed.contentSnippet,
  }))
  const feeds = [...feedQiita, ...feedHugo, ...feedHatena].sort( (a,b) => (a.isoDate >= b.isoDate ? -1:1));

  await writefilePromise('./feeds.json', JSON.stringify(feeds))

/*
  console.log("<html>")
  feeds.forEach( feed => {
    console.log("<div style=\"margin:10px; border: solid, 1px;\">")
    console.log(`<div class='feed_title'>${feed.title}</div>`)
    console.log(`<div class='feed_url'>${feed.url}</div>`)
    console.log(`<div class='feed_isoDate'>${feed.isoDate}</div>`)
    console.log(`<details><div class='feed_content'>${feed.content}</div></details>`)
    console.log(`<details><div class='feed_contentSnippet'>${feed.contentSnippet}</div></details>`)
    console.log("</div>")
  })
  console.log("</html>")
  */
}

const writefilePromise = (path, data) => new Promise((resolve, reject) => {
  fs.writeFile(path, data, (err) => {
    if (err) reject(err);
    resolve();
  });
});

main()

