# Deploying to GitHub Pages
# Source: https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d 
name: github pages

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.4.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.4.0'
    - name: Build Project
      run: |
        cd svelte
        npm install
        npm run build
        cp ../CNAME build/CNAME
    - name: List output files
      run: ls

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./svelte/build
